version: '3.9'

services:
  reverse_proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: reverse_proxy
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - shared_network
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - django_static:/usr/share/nginx/html/static:ro

#==================================================================================================
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput && 
         chmod -R 755 /usr/src/app/staticfiles && 
         python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
      - django_static:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./core/.env
    environment:
      - VAT_RATE=0.19
    depends_on:
      - db
    networks:
      - shared_network

  db:
    image: postgres:16.3-bullseye
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpass123
    ports:
      - "5432:5432"
    networks:
      - shared_network
#==================================================================================================
volumes:
  postgres_data:
  django_static:

networks:
  shared_network:
    external: true
